// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class 123Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void 123() {
    driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto2.forstudy.space/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 832);
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.CssSelector(".btn-link:nth-child(1)")).Click();
    driver.FindElement(By.Id("signupName")).Click();
    driver.FindElement(By.Id("signupName")).SendKeys("afda");
    driver.FindElement(By.Id("signupLastName")).Click();
    driver.FindElement(By.Id("signupLastName")).SendKeys("afd");
    driver.FindElement(By.Id("signupEmail")).Click();
    driver.FindElement(By.Id("signupEmail")).SendKeys("myeddd1@gmail.com");
    driver.FindElement(By.Id("signupPassword")).Click();
    driver.FindElement(By.Id("signupPassword")).SendKeys("Vip330575757!");
    driver.FindElement(By.Id("signupRepeatPassword")).Click();
    driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("Vip330575757!");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
    driver.FindElement(By.LinkText("Profile")).Click();
    driver.FindElement(By.CssSelector(".sidebar > .btn:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.Id("addCarBrand")).Click();
    {
      var dropdown = driver.FindElement(By.Id("addCarBrand"));
      dropdown.FindElement(By.XPath("//option[. = 'Ford']")).Click();
    }
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.Id("addCarMileage")).SendKeys("180");
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.CssSelector(".car_add-expense")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("2000");
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("10");
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("100");
    driver.FindElement(By.Id("addExpenseTotalCost")).Click();
    driver.FindElement(By.LinkText("Settings")).Click();
    driver.FindElement(By.LinkText("Settings")).Click();
    driver.FindElement(By.Id("emailChangeEmail")).SendKeys("papamaksa2000@gmail.com");
    driver.FindElement(By.Id("emailChangePassword")).SendKeys("XDmwjVefy0lCRFN");
    driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
